### ISSUE TITLE
[4.1.0] Missing thin walls

### ISSUE THREAD

**Issue by zebons** [Ultimaker/CuraEngine#1068]
**Application Version**
4.1.0

**Platform**
Windows 64bits

**Steps to Reproduce**
Create a Creality printers and slice with the stl joined 
[WallSize-v3.stl](https://github.com/Ultimaker/CuraEngine/files/3260849/WallSize-v3.zip)

**Actual Results**
Depending on the line width value, missing walls or some lines of the wall at the left side of the model 

**Expected results**
All walls'd be printed as for ultimaker printer

We get missing thin walls with Cura 4.1.0 (same behaviour with Cura 4.0.0) for printers other than Ultimaker.
To proof that, a friend of mine (@trouch) do an stl model (joined to that post). This model has walls varying in width from 0.4mm to 2.5mm steps 0.05mm.
If we slice this model with an Ultimaker printer declared in Cura, all walls are here 
![image](https://user-images.githubusercontent.com/51046171/59018544-6845bd80-8846-11e9-8e11-9869c1834334.png)
If we do the same slice (with same parameters) with a Creality CR-10S we get missing walls at the left :
![image](https://user-images.githubusercontent.com/51046171/59019615-acd25880-8848-11e9-90ec-64f5e2135219.png)
If we select the parameter 'Print thin walls' we sometimes get the wall (or part of it) but with a larger width that it'd be :
![image](https://user-images.githubusercontent.com/51046171/59019805-fae75c00-8848-11e9-9a18-63f31deef95d.png)
With other line width, we can loss more walls 
![image](https://user-images.githubusercontent.com/51046171/59020070-8660ed00-8849-11e9-838d-207d555bac21.png)

Sometimes this parameter has a positive value calculated but the value is too high and some walls are loosen. Ex with a nozzle of 0.4 and line width 0.35, Outer Wall Inset has a calculated value of 0.025 => walls missing
![image](https://user-images.githubusercontent.com/51046171/59025887-75b67400-8855-11e9-8cad-00c5c7cd7d9e.png)
With an Outer Wall Inset parameter value set to 0.022 (lowest value with all walls visibles) => all walls are here
![image](https://user-images.githubusercontent.com/51046171/59026033-d5ad1a80-8855-11e9-9390-2ba170128a2d.png)

**Workaround alternative :**

I find a solution but don't know if it's a good way. If I set a negative value to the parameter Outer Wall Inset.
Example with a Line width 0.4 nozzle 0.4 with Outer Wall Inset -0.003 (the lowest value for that width to get all walls) => all walls are here
![image](https://user-images.githubusercontent.com/51046171/59020706-d4c2bb80-884a-11e9-8972-675bbd56d891.png)
Same line width 0.4 nozzle 0.4 with Outer Wall Inset -0.002 => Missing left wall
![image](https://user-images.githubusercontent.com/51046171/59020870-1d7a7480-884b-11e9-97bc-0ff7ef2ac29e.png)

I search and find a formula that seems to be working for all nozzle size and line width for the Outer Wall Inset parameter. But I don't know if it's a good way to resolve that issue 
                "wall_0_inset":
                {
                    "label": "Outer Wall Inset",
                    "description": "Inset applied to the path of the outer wall. If the outer wall is smaller than the nozzle, and printed after the inner walls, use this offset to get the hole in the nozzle to overlap with the inner walls instead of the outside of the model.",
                    "unit": "mm",
                    "type": "float",
                    "default_value": 0.0,
                    "value": "**(machine_nozzle_size - wall_line_width_0) / 2 - ((machine_nozzle_size * 0.5) - 0.197)**",
                    "minimum_value_warning": "0",
                    "maximum_value_warning": "machine_nozzle_size",
                    "limit_to_extruder": "wall_0_extruder_nr",
                    "settable_per_mesh": true
                },

Thanks for your response

**Comment by zebons** [comment]
My solution doesn't seem to be the best one. I do a test print and if I got all the walls for the print sliced with my modified value, these walls are thicker than they should (2.66mm instead of 2.55mm for the rightest wall). With Cura default value, the leftest wall is missing but all the walls present have the right thickness.
Do you have a better solution to get all the walls with the tight thickness ?

**Comment by Ghostkeeper** [comment]
A part with 0.4mm width using a line width of 0.4mm is expected to disappear. This is because the centreline of the contour is offset by 0.2mm, and the centreline contour is then a polygon without area which will disappear.

It works for Ultimaker printers because we found a line width of 7/8ths the nozzle size to work best. So we have 0.35mm line width and the centreline is 0.175mm away from the edge. This leaves the centreline contour to be a polygon with a 0.05mm width which will not disappear.

Of course, if you perform an additional Outer Wall Inset of 0.025mm, then you end up at an inset of 0.2mm again and your polygon disappears. This is all expected behaviour.

In my experience, adjusting the line width works better than adjusting the outer wall inset. Just make the line width a few micrometres smaller and you won't notice a difference in the print.

> I do a test print and if I got all the walls for the print sliced with my modified value, these walls are thicker than they should (2.66mm instead of 2.55mm for the rightest wall).

Printing lines close together will cause them to heat each other up and then sag. Cura has no compensation factor for this (yet). We don't know yet if software is the best solution to this problem either.

Your solution of adjusting the default of the outer wall inset by a few micrometres is not a good solution in my opinion because the same problem will occur again when you have a model that is a few micrometres thinner.
