### ISSUE TITLE
Override Settings Doesn't Work On Console

### ISSUE THREAD

**Issue by vatansbeytr** [Ultimaker/CuraEngine#1095]
Problem-1 `CuraEngine slice -v -p -j "C:\Program Files\Ultimaker Cura 4.1\resources\definitions\fdmprinter.def.json" -o "C:\Users\xD_xD\Desktop\deneme.gcode" -s infill_sparse_density=50 -l "C:\1.stl"` I just try to change to value of density but It doesn't even work. Hey anyone have a valid def.json file already calibrated because every time I used the console even by default setting giving me different time from cura gui 
Request-if you have a valid file can you upload me.

**Comment by Ghostkeeper** [comment]
As said in #530, this is expected behaviour. CuraEngine only reads the leaf settings. Cura's front-end sets the leaf settings to such values that the desired effect is created. Similar examples are Infill Overlap as percentage or as mm (mm is leading), or Top/Bottom Thickness vs. Layers (layers is leading). In this case, the Infill Line Distance is leading.

If a setting has child settings in fdmprinter.def.json, CuraEngine will not read it.
