### ISSUE TITLE
Extreme Feedrates on Dual Extrusion?

### ISSUE THREAD

**Issue by AbeFM** [Ultimaker/CuraEngine#1096]
**Application Version**
4.1.0

**Platform**
win10

**Steps to Reproduce**
(Create New 2 extruder printer) - I haven't tried skipping this step yet)
Slice object, export g-code
View g-code or print

**Actual Results**
Printer finished one nozzle, then I thought it froze, but it was actually moving ~2-3 mm/s. When it got to the commanded location, everything was fine again. I checked the G-code and saw these suspicious lines on either side of my "extruder end code" "G1  X100 Y100 F1000;Abe Tool 0 End Code"

```
G1 F1800 X172.481 Y168.239 E279.87701
G0 F3600 X173.33 Y168.239
G1 F1800 X173.821 Y168.73 E279.91733
G1 F1800 E271.91733
G1 F17987547480000 Z1.24
G92 E0
G1  X100 Y100 F1000;Abe Tool 0 End Code
T1
G92 E0
M105
M109 S200
G1 F1500 E-6.5
;MESH:dual_extruder_calibration_-_Part_1.stl
G0 F3600 X173.821 Y178.73 Z1.24
G0 X176.126 Y179.735
;TYPE:SKIRT
G1 F17987547480000 Z0.24
G1 F1500 E0
G1 F1350 X175.729 Y180.422 E0.03167
G1 X175.66 Y180.535 E0.03695

```

**Expected results**
G1 F17987547480000 Z1.24
G1 F17987547480000 Z0.24
Both should have some more normal speed like F1000.

**Additional Information**
I just created this printer profile from scratch, and don't think that's the issue. I haven't tried it yet on another printer. I saw this on every filament change.

**Comment by rburema** [comment]
(For future reference: The 'expected results' line is for results you expect, not the actual thing that happens.)

Odd, the suspicious statement occurs nowhere in our code.

However, the rest of the report reads like a known issue: https://github.com/Ultimaker/Cura/issues/5753 In short: Printers that don't have a value set for maximum z speed get the maximum speed possible, light speed. Needless to say, this confuses some printers that didn't anticipate for relativistic speeds.

This has been fixed in 4.2 BETA, and there are several workarounds available even in the current version:
 - manually set the maximum z speed _or_
 - disable z hop _or_
 - adjust the profile of your printer.
