### ISSUE TITLE
CuraEngine from command line dose not support multiple extruders

### ISSUE THREAD

**Issue by mirovskyi** [Ultimaker/CuraEngine#1157]
**Application Version**
4.4

**Platform**
Linux

**Steps to Reproduce**
$ ./CuraEngine slice -v -j ultimaker3.def.json -o output.gcode -e0 -l T0.stl -e1 -l T1.stl

**Actual Results**
output.gcode has only T0 and does not switch to second T1 extruder

**Expected results**
output.gcode has "T1" line for second model T1.stl

**Additional Information**
All profiles I used are original without any changes.

**Comment by Ghostkeeper** [comment]
Yup, seems to be broken. It does load settings for the correct extruder but doesn't load the model. I tried a quick fix but it needs to be debugged properly.

We don't use the debug mode of CuraEngine that often with multiple extruders since it makes things more complex, so I don't know how much force we could put behind this bug...

**Comment by nallath** [comment]
The following code will indeed make everything printed by 1 extruder:
` ./CuraEngine slice -v -j fdmprinter.def.json -o output.gcode -e0 -l T0.stl -j fdmextruder.def.json -e1 -j fdmextruder.def.json -l T1.stl`
But if you do:
The following code will indeed make everything printed by 1 extruder:
` ./CuraEngine slice -v -j fdmprinter.def.json -o output.gcode -e0 -l T0.stl -j fdmextruder.def.json -e1 -j fdmextruder.def.json -l T1.stl -s extruder_nr="1"` 
The second object (T1) will be printed by the second extruder.

The reason for this is because the same extruder definition is used for both extruders, which defines the extruder_nr to be 0. So for both models, the engine gets the instruction to print it with extruder 0.

So you can either ensure that the extruder definitions that you give it set the correct value or you can manually change it.

**Comment by Ghostkeeper** [comment]
Maybe this is something we need to automate. If you put `-e1` then you might reasonably be expecting `extruder_nr` to be set correctly.
