### ISSUE TITLE
Duplicating an object prior to slicing.

### ISSUE THREAD

**Issue by superkamas** [Ultimaker/CuraEngine#1435]
I use iMac 2020 version & up to date. I am trying the Archne Beta V. so when I upload an object & try to duplicate it once or more, the bar at the bottom appears & it freezes. I enclose a picture
<img width="1003" alt="Screenshot 2021-03-22 at 12 05 25" src="https://user-images.githubusercontent.com/81172158/112004603-db9ee900-8b19-11eb-971e-8dcfa8bc78d1.png">

**Comment by fvrmr** [comment]
Hi @superkamas thank you for your report. 
Are you currently running Big Sur? Because we are having some problems with this. See here more: https://github.com/Ultimaker/Cura/issues/8745

We are working on a solution and we already have done a test build that will fix this problem. Progress with the upgrade of the Qt version is still ongoing. There are other crashes still to solve now.

Because this is a duplicate I will close this issue.
