### ISSUE TITLE
AMF file support

### ISSUE THREAD

**Issue by CoDanny** [Ultimaker/CuraEngine#145]
It doesn't seem like CuraEngine can take a AMF files as input. Are there any plans to do this in the Engine?

I know that the Cura application can do this, but it would be beneficial to accept AMF files as input in the engine too.

**Comment by Renha** [comment]
That's sad. Because CuraEngine is used not only in Cura, while CuraEngine is only engine in Cura - looks like that functionality could be moved

Additional possibility of AMF files is rounding of polygons - how would you transfer that info from Cura to CuraEngine when elliptic moves would be added to printer firmwares? You would need to have at least part of AMF-worker in Engine anyway. So why not move?

**Comment by BagelOrb** [comment]
Smooth moves are simply not supported by the slicer, and won't be forat least the coming years. Almost all of the engine has to be rewritten.

I am glad to accept a pull request for reading AMF files though. However it only makes sense to use such a feature if you could also apply a rotation matrix etc within the engine.

I hope you are willing to implement these features; I can't work on them as they don't contribute to Ultimaker..

**Comment by nallath** [comment]
Not only do we need to rewrite the engine, a firmware rewrite would also be required.

**Comment by Ghostkeeper** [comment]
"Rewrite" is a big word. It'd be easiest to just discretise the curve to a bunch of small triangles when loading the AMF file.

Ultimaker would load the AMF file in the front-end though, since being able to load AMF files in the engine has no value for the average user. It is not translated through to the front-end: The file is already converted to a bunch of vertices and faces for communication, so that we wouldn't have to implement the communication for different file types. It'd have to be implemented again for the engine. That's why the engine will only have AMF support if it's implemented by the community.

**Comment by daid** [comment]
Actually, AMF says you need to sub-triangulate with normals. No real curves there. It wouldn't be a whole lot of work to add that part to the engine. And the frontend just needs to send normals next to vertices.

Remember, the only reason the engine reads STL for us is for debugging goals.
