### ISSUE TITLE
Why has input-file to end on ".stl"

### ISSUE THREAD

**Issue by muggy83** [Ultimaker/CuraEngine#1484]
I was using CuraEngine to be called from a Python Flask Application, which is storing the STL in a temporary file.
It took me hours to find out, that the inital problem was, that my temporary file was not ending with ".stl".
Is there a technical reason, that the input must have a .stl file type? If not I would recommend to either
- allow any (and none) file type or
- bring up a human readable error-message like "Given file is not a STL"

**Comment by nallath** [comment]
There isn't really a technical reason for it, but the CLI is mostly used for debugging by us. The engine itself only supports STL's and uses a pretty naive way of checking that (it checks if the filename ends with ".stl" or ".STL").

I will add a warning if it was unable to load the file so that it's at least clear that this is what the engine expects.
