### ISSUE TITLE
How to convert filling rate and filling space

### ISSUE THREAD

**Issue by Ccaomei** [Ultimaker/CuraEngine#1515]
Hello everyone, I would like to know how to calculate the conversion between filling rate and filling spacing. There is another question that needs to be confirmed. Is the unit of coordinate points filled by Curaengine in microns?

**Comment by Ghostkeeper** [comment]
It's worth mentioning perhaps that the formula listed by Piezoid is executed by Cura's front-end. CuraEngine doesn't listen to the Infill Density setting at all, only to the `infill_line_distance` setting. So if you're not working via the Cura front-end, make sure to set `infill_line_distance` manually.

The mistake Ccaomei made in his formula was to take `infill_sparse_density` as a value between 0 and 1, instead of a percentage between 0 and 100. By dividing the density by 100 the line distance would indeed end up at 410mm.

The `E` coordinate is calculated by multiplying the line width, layer height and line length to get the extruded volume. This volume then gets divided by the cross-sectional area of the filament if the g-code needs to be output as filament length (or just output as volume if the g-code flavour is volumetric). Documentation about that is here: https://github.com/Ultimaker/CuraEngine/blob/master/docs/gcode_export.md#the-e-parameter
