### ISSUE TITLE
Cura does not fully comb octopus printed at half size

### ISSUE THREAD

**Issue by lawrencejohnston** [Ultimaker/CuraEngine#22]
(moved from https://github.com/daid/Cura/issues/550)

When slicing http://www.thingiverse.com/thing:8896 at half size with 3 perimeters Cura 13.06.05 does not comb when moving between the tiny bits of infill on the legs. See the jumps between the legs in the attached image.

(could be a dup of https://github.com/Ultimaker/CuraEngine/issues/6, but I can't tell from the descriptions)

![ec5c4666-151a-11e3-9c18-8dde0d38c586](https://f.cloud.github.com/assets/1351139/1103953/79651a14-18d2-11e3-807a-816c730f9774.png)

**Comment by BagelOrb** [comment]
Finding the middle between perimeters is quite difficult. The area between the perimeters can be of arbitrary shape. There is no algorithm to find the single middle line of an arbitrary polygon, since it is underdefined.

Suppose the polygon looks like a pentagon, what would be the middle line? The question doesn't make sense.

However, I've been thinking about the problem of finding the middle line of a nearly linear piece in a polygon, but I still can't think of a solution.
