### ISSUE TITLE
15.09.85: Not filling small gaps

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#253]
The gap filling seems very inconsistent remove & compensate for wall overlaps disabled:

![image](https://cloud.githubusercontent.com/assets/12439543/10261235/db3dc488-6953-11e5-9da2-8d17058fa8bb.png)

**Comment by CCS86** [comment]
It would be really great if Cura could identify these opportunities for an additional shell pass that is less than a nozzle width. The volumetric calculation could now be based on the width of the section, rather than the width of the nozzle.

**Comment by BagelOrb** [comment]
If you remove the overlapping walls, they will be gone. It's no use to then compensate for overlap, since the overlaps are already gone.

Perhaps these two boolean settings should be merged into a single drop down menu..

It's nearly impossible to identify these cases automatically. That will be out of scope.

**Comment by CCS86** [comment]
That sounds like a separate issue to me. I just mentioned those settings in case they have the capacity to avoid filling these areas. 

@Ghostkeeper  This seems more like a bug in the gap filling to me. At least for the gap near the through hole. There is clearly enough room for a nozzle width infill there.

In regards to the long skinny gaps: on some layers they are filled and others they are not. The model thickness is uniform.

**Comment by CCS86** [comment]
Model: https://dl.dropboxusercontent.com/u/60958586/Controller.stl

**Comment by BagelOrb** [comment]
Yes. Remove overlapping wall parts avoids filing those areas.

For normal slicing you would need twice the nozzle size for it to be filled. For gaps between one and two times the nozzle size you need to enable compensate wall overlaps. For gaps between zero and one you need to enable fill inter perimeter gaps.

For gaps exactly the nozzle size the algorithms might alternate between inter perimeter gaps and overlapping walls due to rounding errors.

**Comment by BagelOrb** [comment]
Remove overlapping wall parts is a fast algorithm which is on the safe side (no overextrusion) of doing it 'wrong'. It removes wall parts on purpose.

**Comment by CCS86** [comment]
@BagelOrb 

I haven't seen a "fill inter perimeter gaps" setting. Where can I find it?

**Comment by CCS86** [comment]
![image](https://cloud.githubusercontent.com/assets/12439543/10271294/d0d1282c-6ad0-11e5-9656-43e958c18c36.png)

**Comment by CCS86** [comment]
Vs old faithful:

![image](https://cloud.githubusercontent.com/assets/12439543/10271486/b1233060-6ad5-11e5-93e2-1ba06a7f8153.png)

**Comment by BagelOrb** [comment]
It's called 'fill gaps between walls' in the GUI...

**Comment by BagelOrb** [comment]
The 'old faithful' prints walls at very sharp angles which is impossible in practice. There you will see a bit of over extrusion. The new Cura performs under extrusion instead of over extrusion, when you enable 'fill gaps between walls'.

**Comment by CCS86** [comment]
Looking better in the .90 build. 

There is still a visualization issue:

![image](https://cloud.githubusercontent.com/assets/12439543/10310712/f66dc700-6c08-11e5-96c6-14f19be4f3b2.png)

![image](https://cloud.githubusercontent.com/assets/12439543/10310717/fadc8ab0-6c08-11e5-9028-4949d4d65701.png)
