### ISSUE TITLE
Compile Error, protobuf, not a member

### ISSUE THREAD

**Issue by w41ru5** [Ultimaker/CuraEngine#262]
I am running Arch Linux 64bit and trying to compile the cura-build 15.10 repo, but I am running into a problem at CuraEngine. I have attached the output as a file due to the lengthy text, but it looks like it has something to do with protobuf. I am using google/protobuf compiled from commit 49f24af... Is there something else I am missing?

Edit: I am having trouble with the attachment feature while I investigate why it's not taking my file here is a clip of the output:

[ 97%] Building CXX object CMakeFiles/CuraEngine.dir/Cura.pb.cc.o
.../cura-build-15.10/build/CuraEngine-prefix/src/CuraEngine-build/Cura.pb.cc: In member function ‘virtual bool cura::proto::ObjectList::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’:
.../cura-build-15.10/build/CuraEngine-prefix/src/CuraEngine-build/Cura.pb.cc:523:15: error: ‘ReadMessageNoVirtualNoRecursionDepth’ is not a member of ‘google::protobuf::internal::WireFormatLite’
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(

**Comment by Ghostkeeper** [comment]
Ah, I wondered about this. Ultimaker's projects forked from protobuf a long time ago, because back then we wanted some things that Protobuf didn't offer at the time, such as CMake. Our version is [here](https://github.com/Ultimaker/protobuf).

Since then Protobuf has implemented many of those things itself. We've also made some bugfixes though (that should've been sent upstream maybe but weren't). It seems that Google's version isn't quite compatible with ours any more.

I suggest for now that you compile with [Ultimaker's fork of Protobuf](https://github.com/Ultimaker/protobuf).

**Comment by Ghostkeeper** [comment]
Though it looks like this was made with the Cura-build repository.

**Comment by awhiemstra** [comment]
cura-build normally builds the Ultimaker Protobuf clone of Protobuf. However, if you have Protobuf 3 locally installed CMake can get confused and use the local install of Protobuf for building Arcus/CuraEngine. If you can provide the full output, I can verify that that is what is happening here.

**Comment by w41ru5** [comment]
Alright, I uninstalled all my protobuf compiles and reran the build and it went through fine. Thanks guys!
