### ISSUE TITLE
Support roofs due to XY separation

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#285]
Hi guys,

Is there a setting that can help control this support being generated in mid air? I have not had much luck yet.

![image](https://cloud.githubusercontent.com/assets/12439543/11798466/9dcdf30e-a290-11e5-98d4-226f169494b8.png)

**Comment by BagelOrb** [comment]
You could set the support bottom stair step height to zero.
Op 15 dec. 2015 01:28 schreef "CCS86" <notifications@github.com>:

**Comment by BagelOrb** [comment]
If you select support pattern grid it will not generate such mid air blips.

**Comment by BagelOrb** [comment]
In your picture these mid air pieces are generated by the support roofs.

You could also try the Concentric support roof pattern.

I have no idea how to solve this problem. I think it would happen quite often when using zigzag support with lines roof.

**Comment by CCS86** [comment]
It seems to be due to the fact that the inside radius of the part causes Cura to generate roof closest to the model first. Because of the large XY distance I specified, I did not expect this to happen. It's a 1mm radius, with an XY separation of 1.5mm.

Maybe there is a small error in how that calculation is done?

**Comment by BagelOrb** [comment]
If the support looks like this
```
 __
/  \
|  | (side view)
```

Then the horizontal part as well as the diagonal parts will get support roof. The diagonal parts also have a horizontal aspect.

The way support is generated is as follows: first the volume in which to generate the support structure is calculated and then the roof is generated as if it was top skin.

I now see that this can be improved upon, since some diagonal parts are introduced by the x/y separation.

**Comment by BagelOrb** [comment]
Fixed
