### ISSUE TITLE
Merge Infill Lines occurs too often

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#286]
Hi guys,

I'm seeing some issues with gap filling. I have it turned on everywhere in this gcode, but it is still struggling:

![image](https://cloud.githubusercontent.com/assets/12439543/11798559/8f6b23bc-a291-11e5-920a-fabe5efe9b23.png)

More trouble:
![image](https://cloud.githubusercontent.com/assets/12439543/11798567/9b9c296a-a291-11e5-9a5d-f4f575c245e8.png)

I'm not sure if this is a display issue in repetier, or what, but this is with coasting turned off to see if it played a part:
![image](https://cloud.githubusercontent.com/assets/12439543/11798708/ee310fdc-a292-11e5-8682-c2109667f790.png)

Yikes!
![image](https://cloud.githubusercontent.com/assets/12439543/11798732/175b0840-a293-11e5-8bcb-aa7ccbd7f51e.png)

**Comment by CCS86** [comment]
Gcode:

[UMO_Idler Carrier_nocoast.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/61918/UMO_Idler.Carrier_nocoast.gcode.txt)

Model:

**Comment by CCS86** [comment]
Won't accept the zip for some reason. Just drop the .txt extension and unzip:

[Idler Carrier.zip.txt](https://github.com/Ultimaker/CuraEngine/files/61919/Idler.Carrier.zip.txt)

**Comment by BagelOrb** [comment]
The bug you are seeing in the first two images is a bug of mergeInfillLines. When CuraEngine sees consecutive small line segments `iiiii` it will convert them into one line segment in the orthogonal direction `====`.

The bug is that it apparently also converts non-consecutive small line segments `i  i  i` into a line segment `-------`.

This bug can be seen in the first picture: on the left side they are combined and on the right side they are not.
On the right upper side of the second picture they even seem to have been combined in a quite horrible fashion.

I also think I'm seeing both skin and infill on 100%. I recommend making the top or bottom skin practically infinite, so that all infill is replaced by skin. That wat you don't get the separate areas on the other sides of the walls where the pointy things are.

The third picture seems to be of a different layer - where the pointy things are connected; otherwise it might be a Repetier visualization bug. Try viewing that layer in Cura 15.04 to see if the pointy things really are connected.

**Comment by BagelOrb** [comment]
I'm afraid this will not be solved in the coming release, but the one after..

**Comment by CCS86** [comment]
You are correct, the 3rd picture is a different layer. These are some printed threads, with the screw axis on the XY plane, if that helps explain it. 

I should have drawn arrows there too, but I posted it because the gap filling looked bizarre.

**Comment by CCS86** [comment]
Is it possible to have a flag when 100% infill is used, that it should skip the algorithm which tries to section off infill regions which are near overhangs, and fill them 100%.

**Comment by BagelOrb** [comment]
If you select 100% infill in the frontend, the infill is automatically
turned off, bottom layers set to 9999 and top layers set to 0...
This is done in the frontend, not in CuraEngine.
Op 15 dec. 2015 21:11 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
So, why is it that areas which will soon become overhangs, are still sectioned off and filled separately. I thought that feature was meant to help densify sparse infill to better support overhung areas.

**Comment by CCS86** [comment]
I am not seeing the behavior you mentioned:

"If you select 100% infill in the frontend, the infill is automatically
turned off, bottom layers set to 9999 and top layers set to 0..."

With infill set to 100% "lines" and bottom layers 5, the 12th layer looks like this:

![image](https://cloud.githubusercontent.com/assets/12439543/11829444/3d6807fc-a362-11e5-9526-ee5212231d3e.png)


Changing bottom layers to 100, and it looks like this:

![image](https://cloud.githubusercontent.com/assets/12439543/11829451/4f246dc8-a362-11e5-89b9-945f119ca2ad.png)



[UMO_Sheave i-nocoast-5-bot.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/63432/UMO_Sheave.i-nocoast-5-bot.gcode.txt)
[UMO_Sheave i-nocoast-100-bot.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/63433/UMO_Sheave.i-nocoast-100-bot.gcode.txt)


Model:
[Sheave i.stl.txt](https://github.com/Ultimaker/CuraEngine/files/63434/Sheave.i.stl.txt)

**Comment by CCS86** [comment]
It gets soooo close on some of these layers, then just falls apart in a couple spots!

![image](https://cloud.githubusercontent.com/assets/12439543/11829570/cdd5705e-a362-11e5-8e0c-6dc56dfc6a38.png)

**Comment by BagelOrb** [comment]
Perhaps this has been fixed in between your version and mine, cause I am seeing the 100% infill thing working.

![curaengine_bad_support](https://cloud.githubusercontent.com/assets/8895761/11845424/1d44e10e-a414-11e5-823c-2ae59ea1f59e.png)

Your last picture is another problem of Merge infill lines again :(

**Comment by BagelOrb** [comment]
Ah no your last picture is not a mirge infill lines issue per se. The thing is that the infill is converted to a smooth round line everywhere, except for the places where the infill is approximately aligned with the direction of the circle. It's a limitation of how that small area is converted into two long circular lines.
That will not be fixed any time soon. :/

**Comment by CCS86** [comment]
Shoot, that's disappointing. Is that feature useful in other situations?

**Comment by BagelOrb** [comment]
I fixed this issue in the current release accidentally, so perhaps it will be in the next release after all, instead of the one after that.

**Comment by BagelOrb** [comment]
Even with circular infill areas, the revised algorithm works better! :D

**Comment by CCS86** [comment]
Excellent, nice work my friend!

Is there anyone we can tag here who might be willing to compile a new beta build? I've got some new prototype parts to print out and would love to test some of the fixes.

**Comment by Ghostkeeper** [comment]
I can send you a build for Linux if you like, or Windows 32-bit with some work, but other ones have to wait. @awhiemstra is the only one able to make a proper OSX build here and he's on vacation.

Our weekly builds have moved internal since our testers need a build that includes secret information, so we can't share those, but I can make a build without all that for Linux or Win32 (not 100% sure about Win32 but it should work).

**Comment by CCS86** [comment]
That would be great. I've been using Win64, but 32 should be fine.

**Comment by Ghostkeeper** [comment]
I'll give it a try for you once I'm home tonight. No promises though! :stuck_out_tongue: I'll keep you updated. The Win64 build has some problems with building Python libraries which are out of my league.

**Comment by CCS86** [comment]
:+1:

**Comment by Ghostkeeper** [comment]
I successfully built it for win32 but running it caused a complaint that it couldn't find Qt libraries, and it became fairly late (2:00). Going to try again tonight.

**Comment by CCS86** [comment]
I'll sign an NDA if that makes things easier ;)

**Comment by Ghostkeeper** [comment]
It would, but I'm not at liberty to make the decision to offer that to you :wink: I'd only distribute public builds here. No luck so far though, still getting a runtime error after running the installed binary: Ultimaker/cura-build#26 . A senior developer is working with daily internal builds right now too, so if he's having success I could ask him.

To keep this issue thread on topic, I'll try to keep radio silence from now on unless I can offer a (non-secret) build and you'd like to help test the fix.
