### ISSUE TITLE
Infill Wipe Distance not Functioning?

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#311]
Here, I have it set to .35mm, so it should be very evident, but looks like no infill wipe at all:

![image](https://cloud.githubusercontent.com/assets/12439543/13358368/931632f0-dc74-11e5-9bbb-c62c2e193a2e.png)

Any ideas?

Thanks

**Comment by CCS86** [comment]
Ah, looks like I had bottom layers cranked way up.

I'm assuming that infill wipe is disabled on bottom/top layers. Is this intentional?

**Comment by BagelOrb** [comment]
Well it's kind of intentional - if that's a thing.

For infill the adhesion to the walls is more of a problem.

Do you think it would be better to have it on the skin infill as well?

Or would it be better to introduce yet another setting for skin wipe?
Op 26 feb. 2016 23:10 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
I think it's helpful during solid infill as well. It helps to fill in the
tiny "stair step" gaps between adjacent infill passes, without commanding
extra extrusion via infill overlap.

I think it could just be applied via the same parameter. Or if some are
very opposed to it, maybe a check box to disable wipe on skin.

**Comment by BagelOrb** [comment]
Fixed via the same parameter.
