### ISSUE TITLE
Milestones for print

### ISSUE THREAD

**Issue by Taiko1976** [Ultimaker/CuraEngine#333]
**Issue:**
Currently the slicer creates the code for the print according to the model provided to the slicer. The parameters used for the g-code are provided by the settings of CuraEngine and by the settings of the printer itself. Once the slicing is done these settings are used for the whole print out and can only be changed manually through the HMI (e.g. RepetierHost). However to do this you have to sit in front of the printer and monitor the progress thoughout the print to adjust the settings accordingly.

**Improvement:**
From my perspective any print has several milestones that need to be addressed accordingly to facilitate a successful print. Each milestone can have different settings to have the desired effect (e.g. when printing the first layer you want to go really slow and easy to make sure that your objekt will stick to the heat bed nicely). Partly there is already the possibility to do this, but not all the way through the print.

To add more flexibility to the process I'd propose to implement milestones for the print. Each milestone has a seperate set of settings that can be changed accordingly to the needs of each specific milestone.

I'd propose the following mile stones during print:
- Raft
- First Layer
- Support Structure
- Model
- Last Layer

I'd propose the following settings for each milestones:
General settings:
- Head bed temperature
For each extruder present in the printer:
- Extruder temperature
- Extruder flow rate
- Speed of print
- Cooling

This way you can plan your print more detailed. Especially when using multiple extruders with different materials (like PLA for model and PVA for support structures and rafts) you want to have different settings during the print. 

**Example A:**
When printing PVA it works much better when using a temperature like 220°C during print. This works fine while printing because the material is heated and extruded right away. However when the extruder with the PVA is on stand by the temperature is too high. The PVA will be "cooked" to the point where is gets solid and clogges up the extruder. Now if you can reduce the temperature of the extruder during standby this effect will be lessened or it will not happen at all. However to be efficient you have to time the cooling and heating of the extruders accordingly. Otherwise the print will be prolonged because the printer has to wait for the extruders to head up after each extruder switch.

**Example B:**
When printing the first layer of the model or the raft you have to go really slow to be sure that the extruded filament will stick to the heat bed. This is crucial to be able to print your models without problems during the print. To improve stickiness you can change the settings of your heat bed or of your extruder when printing the first layer (e.g. increase heat bed temperature for PVA to increase adheasion to the heat bed or increase extruder temperature for PVA for the first layer to increase the stickiness of the filament when extruded).

**Conclusion:**
By being able to "plan" your print you are able to be more flexible with your print and ultimately the printing process will be more stable. It add's a powerful flexibility when using different materials. Configuring your printer will be more flexible and therefore the results will be better and more stable.

If you have any more questions feel free to contact me. 

Thanks and keep up your great work!
Regards, Bernd

Thanks and keep up your great work!
Regards, Bernd

**Comment by BagelOrb** [comment]
Dear Bernd,

Please refrain from conceptualizing the changes you want into a bigger picture. The concept of milestones ultimately boils down to implementation details and conceils the fact that you are actually asking for several features.

To better reply to those feature requests it's better to file separate github issues. Then we can handle them separately and none will get forgotten.

It sounds to me like you're using Cura 15.04. Try out the new beta! It's got a couple of features which the old Cura didn't have. Dual extrusion is not yet supported, however. We are focussing on reintroducing dual extrusion for the next major release.

1) Print head temperature can already be adjusted per extruder, but there is currently no frontend interface for it.
2) Print speed can be adjusted separately for each feature type (skin, outer walls, support, etc.)
3) Flowrate per feature type is dubitable, but I'm looking into exposing this to the frontend.
4) Cooling is not adjustable per feature type. However, the fans mostly cover the area next to where you are currently printing, so it is likely to cover other feature types than the current. I'm afraid that when you set the fans high for support to get less layer bonding, the layer bonding in the model will also get less, leading to worse printing quality.
5) The bed temperature can only change quite slowly, due to the way printers are built; it doesn't make much sense to require different bed temperatures for different parts of a print.
6) Changing the head temperature per feature type is currently intractible, because changing the temperature actually takes longer than it generally takes to print one feature type. This feature would generally lead to instable temperatures which fluctuate too much to get stable print results.

Looking forward to your reply.
