### ISSUE TITLE
Get rid off traveling during infill

### ISSUE THREAD

**Issue by ynilsiam** [Ultimaker/CuraEngine#340]
Hi,

Is there any settings that would get rid off traveling during the infill?
So that the infill would start from the one of the corner and continue until fill the whole layer without traveling.

Thanks,

**Comment by BagelOrb** [comment]
Well, if your layer part has several infill parts then it's impossible.

However, you could select the ZigZag infill option and then almost all
infill will be a continuous line.

Do note that we found the ZigZag pattern generally to work worse than lines
infill.
Op 11 mei 2016 07:02 schreef "ynilsiam" <notifications@github.com>:

Hi,

Is there any settings that would get rid off traveling during the infill?
So that the infill would start from the one of the corner and continue
until fill the whole layer without traveling.

Thanks,

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/340>
