### ISSUE TITLE
2.1.2 Odd moves

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#357]
Hi guys,

These sequence seemed very out of place when watching the print. Do you know why it was generated?

![image](https://cloud.githubusercontent.com/assets/12439543/16181224/84b89c14-365d-11e6-91aa-902c4c6c4f74.png)

[model.stl.txt](https://github.com/Ultimaker/CuraEngine/files/322597/model.stl.txt)

[gcode.txt](https://github.com/Ultimaker/CuraEngine/files/322596/gcode.txt)

**Comment by BagelOrb** [comment]
I don't know. Did you set infill to 100%?

It's better to set the top bottom thickness to 9999 instead.
Op 20 jun. 2016 03:37 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
Yes, it is 100% lines. 

I don't like using bottom layers, because it used to disable infill wipe, and now maybe combing?

**Comment by BagelOrb** [comment]
If you set combing to No Skin then it won't do combing in 100% mode.

Why would you want infill wipe when you only have skin?

Why do you think the order of lines is weird? It first does the infill and
then the top bottom skin. This is to minimise the number of changes in
nozzle pressure.
Op 21 jun. 2016 06:13 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
It's not the order of the lines I find odd; it's that they exist at all. That space should easily fill without gap filling, and did on the prior layers. Have a look at layers 1 and 2, to see what I mean.

I'm not sure I understand the question about infill wipe. I want infill wipe everywhere, because it reinforces the bond between infill and perimeters. I don't know what you mean by "only have skin".

**Comment by Ghostkeeper** [comment]
When infill is set to 100%, by default it makes the number of skin layers 999999 (because that tends to work better). He's therefore assuming that you only have skin and no actual infill.

**Comment by CCS86** [comment]
Do "top" and "bottom" layers both classify as skin?

I feel like in one of the recent releases, with 100% infill set, I could see the difference between bottom layers and normal infill, by the presence of infill wipe.

**Comment by Ghostkeeper** [comment]
Yes, they are both skin.

**Comment by CCS86** [comment]
Do you guys agree, that this sequence of moves does not make sense?

**Comment by BagelOrb** [comment]
No, to me or makes perfect sense. Think about what happens when you make the infill 95%. Then the lines won't line up any more. The fact that the infill and the skin line up is just a coincidence which makes it *seem* like it's doing word detours.

The thing is that you'd want to do the infill lines and skin lines separately because they might have different speeds and changing speed a lot of times affects print quality.

You want to first print all infill lines and then all skin lines.

**Comment by Ghostkeeper** [comment]
To me it still doesn't make sense :disappointed:

If skin layers is set to 999999, there should be no infill lines in the picture. Nothing is done separately.

**Comment by CCS86** [comment]
I don't understand your reasoning @BagelOrb 

There are three, discrete areas that are being filled completely out of order with the rest of the infill. They just so happen to be symmetrically placed relative to the part geometry. I can't see the value in taking what should rightly be continuous infill lines throughout the entire infill region, and breaking it up like this.

I have noticed this sort of behavior before, but never isolated it. It definitely has the capacity to lower print quality.

**Comment by BagelOrb** [comment]
As I understood it you set the infill to 100% and then changed the top and
bottom skin back to the normal amount of layers.

I simply suggest that you leave the bottom skin count at 99999 if you don't
like this outcome.

The reason that it happens is that the infill areas are printed separately
from the top/bottom skin. The fact that the infill line distance is the
same as the skin line distance doesn't change that.
Op 24 jun. 2016 06:13 schreef "CCS86" <notifications@github.com>:

I don't understand your reasoning @BagelOrb <https://github.com/BagelOrb>

There are three, discrete areas that are being filled completely out of
order with the rest of the infill. They just so happen to be symmetrically
placed relative to the part geometry. I can't see the value in taking what
should rightly be continuous infill lines throughout the entire infill
region, and breaking it up like this.

I have noticed this sort of behavior before, but never isolated it. It
definitely has the capacity to lower print quality.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/357#issuecomment-228254275>,
or mute the thread
<https://github.com/notifications/unsubscribe/AIe9EUywpUSJ2LSF4D3d0issuVxTX5rrks5qO1lmgaJpZM4I5TPK>
.
