### ISSUE TITLE
scale gcode

### ISSUE THREAD

**Issue by roboticsexpert** [Ultimaker/CuraEngine#362]
hi .

how can i scale model for generating gcode ?

**Comment by BagelOrb** [comment]
You could use a GUI frontend.

Alternatively, write the code to pass a transformation matrix via the
settings and submit a pull request.
Op 25 jun. 2016 06:15 schreef "Mahdi Youseftabar" <notifications@github.com
>:

hi .

how can i scale model for generating gcode ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/362>, or mute the thread
<https://github.com/notifications/unsubscribe/AIe9Ea1mLO-OVpbmtumSkAFj5tXhEHH0ks5qPKtqgaJpZM4I-QzS>
.
