### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [Ultimaker/CuraEngine#39]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/Ultimaker/CuraEngine/blob/744f09eefbc80026e1863887db1ae0e425c75aa1/main.cpp#L362 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by BagelOrb** [comment]
Currently the backend crashes and the OS clears all memory used by CuraEngine. There is no need to do it neatly.

However, at some point we want to look at passing errors back to the front-end, so that we can communicate them to the user and/or automate error reports to our servers.

As for now we don't distinguish between erroneous setting values (e.g. a layer thickness of zero) and bugs in the engine. If it slices, it slices.

**Comment by daid** [comment]
Only thing throwing exceptions right now is the clipper library, and those are caught just fine (search for "try" in main.cpp)
