### ISSUE TITLE
Extraneous support material added when placement is "Touching Building Plate"

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/CuraEngine#418]
Hi,
I am seeing an issue with Cura 2.3.1 where a small pad of support material is incorrectly added under a region which would have support added higher up in the print if placement was "Everywhere". If I set the placement to "Everywhere" this pad goes away and the support is added above when the void is reached.

So, here's a screenshot of the pad that shouldn't be there. It's the light blue region on top of the darker blue area.

![screenshot_2016-12-09_10-09-30](https://cloud.githubusercontent.com/assets/585618/21045335/dbae037a-bdf7-11e6-8202-94e7561a1e82.png)

And here's a screensot showing what is above that area. Basically, there's a solid region that extends over the whole supported region and then on one side of that is a taller solid region that has a hole in it. It's the area under the hole that gets covered by the unwanted pad.

![screenshot_2016-12-09_10-10-21](https://cloud.githubusercontent.com/assets/585618/21045356/e9a7314a-bdf7-11e6-96a2-3cbd0510b651.png)

**Comment by BagelOrb** [comment]
I don't really understand.

Did you color this patch yourself?

Is this patch on a different layer than the big square of support?

Could you please attach your model to this issue?

This might very well have to do with a bug I solved for Cura 2.4 in which small patches of overhang would create support on every layer, since at the top of the round hole there is a really small overhang area. The same doesn't hold for the top of the hexagonal hole, so I'm quite surprised to see this.

**Comment by smartavionics** [comment]
No, I didn't colour the patch, that's what Cura is displaying

Yes, the patch is above the big square of support  - it is printed on what should be an empty layer (between support and the model).

I have copied the model to

[https://www.dropbox.com/s/8ddm5n5wrz67nfr/KX_magni_combo_mount.gcode?dl=0](url)

**Comment by smartavionics** [comment]
Oops, here's the stl.

[https://www.dropbox.com/s/t15tyvs33f4uxr4/magni_combo_mount.stl?dl=0](url)

**Comment by Ghostkeeper** [comment]
It's displaying the top few layers in a brighter colour. That's why that patch shows up brighter.

**Comment by smartavionics** [comment]
Sure, but the patch should not be there at all!

That layer should be empty in the support region because it's the gap between the support and the area above that is being supported.

**Comment by Ghostkeeper** [comment]
I can't reproduce it exactly (I tried also with Kossel Mini but I don't have the exact same printer).

But it does seem to produce a little patch there:
![bitofsupport](https://cloud.githubusercontent.com/assets/2448634/21052020/3040a8e0-be23-11e6-93e6-ea5b8513e7dd.png)

**Comment by smartavionics** [comment]
Also, there's something odd about the interface region below where the patch occurs, as shown here

![screenshot_2016-12-09_14-22-06](https://cloud.githubusercontent.com/assets/585618/21052069/126fef0e-be1b-11e6-8c5a-42982459968e.png)

See that weird triangular feature. It has offset the filament strands. You can see that clearer using the gcode viewer in s3d

![screenshot_2016-12-09_14-26-41](https://cloud.githubusercontent.com/assets/585618/21052188/8b39130c-be1b-11e6-8799-27e6d4f2b631.png)

**Comment by BagelOrb** [comment]
I could reproduce it on 2.3, but not in the Cura 2.4 pre-beta, so this bug has been solved.

The triangular pattern is just created because it wants to print support a little bit further out at that spot. That's a bit ugly; the only reason there is more support there is to eventually support the round hole, but it cannot support it due to the restriction of support only being placed on the build plate. I wouldn't call that a bug.
