### ISSUE TITLE
Loading model file

### ISSUE THREAD

**Issue by ghost** [Ultimaker/CuraEngine#436]
Why when I load a model (.stl or gcode doesn't matter) 95% of the time I never see the model in Cura.  Before loading I make sure I've cleared the platform and I've also right clicked and deleted all before trying to load a new one.   I've tried both version 14 and 15 with the same issue.  Is it something I may be doing wrong or is this and issue that requires a special procedure

**Comment by BagelOrb** [comment]
Try Cura 2.

Cura 1.15 is not actively being developed any more.

Op 11 jan. 2017 18:31 schreef "mikeatsr" <notifications@github.com>:

Why when I load a model (.stl or gcode doesn't matter) 95% of the time I
never see the model in Cura. Before loading I make sure I've cleared the
platform and I've also right clicked and deleted all before trying to load
a new one. I've tried both version 14 and 15 with the same issue. Is it
something I may be doing wrong or is this and issue that requires a special
procedure

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/436>, or mute the thread

**Comment by mikeatsr** [comment]
Thank you, I will try that..
 

    On Wednesday, January 11, 2017 12:06 PM, Tim Kuipers <notifications@github.com> wrote:
 

 Try Cura 2.

Cura 1.15 is not actively being developed any more.

Op 11 jan. 2017 18:31 schreef "mikeatsr" <notifications@github.com>:

Why when I load a model (.stl or gcode doesn't matter) 95% of the time I
never see the model in Cura. Before loading I make sure I've cleared the
platform and I've also right clicked and deleted all before trying to load
a new one. I've tried both version 14 and 15 with the same issue. Is it
something I may be doing wrong or is this and issue that requires a special
procedure

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/436>, or mute the thread
