### ISSUE TITLE
How does CuraEngine get slice layer parts with overlap polygons?

### ISSUE THREAD

**Issue by zidong404** [Ultimaker/CuraEngine#467]
Hello, I am Reading the source code.Now I know  how to Make 'LayerParts' by closed polygongs, My question is:If some of the polygons which created by Slicer() are overlapped by each other,how does the Clipperlib generate correct 'LayerParts' in the first step.The code is  `clipper.Execute(ClipperLib::ctUnion, resultPolyTree);`that means the default fill type is even-odd,fallowing is my test:
![test](https://cloud.githubusercontent.com/assets/22258646/23218129/5b1246fa-f956-11e6-92ba-63304b8684f3.jpg)
    The left is my model, as you can see the bottom suppport parts are overlaped.I've got the firs layer's slice polygons(use my own algorithm ), and the right-up is the result generate by Clipper with none-zero fill type, the right-down is even-odd.Obviously 'none-zero' filltype is correct in this test.
    I am looking for the codes that handling overlape polygons  in curaengine, but I didnt find it,so I was confused how dese curaengine fix this. Follwing is the layer view of the model's first layer in Cura, and Cura makes the correct layerpart.
![test2](https://cloud.githubusercontent.com/assets/22258646/23219628/93131a26-f95a-11e6-8804-5aa4aac6c729.jpg)
     Waiting for answers ,thanks!

**Comment by BagelOrb** [comment]
Cura frontend has a setting Union All under the mesh fixes category, which
determines which fill the is used.

Op 22 feb. 2017 16:58 schreef "zidong404" <notifications@github.com>:

Hello, I am Reading the source code.Now I know the how to Make 'LayerParts'
by closed polygongs, My question is:If some of the polygons which created
by Slicer() are overlaped by each other,how does the Clipperlib generate
correct 'LayerParts'.The code is clipper.Execute(ClipperLib::ctUnion,
resultPolyTree);that means the default fill type is even-odd,fallowing is
my test:
[image: test]
<https://cloud.githubusercontent.com/assets/22258646/23218129/5b1246fa-f956-11e6-92ba-63304b8684f3.jpg>
The left is my model, as you can see the bottom suppport parts are
overlaped.I've got the firs layer's slice polygons, and the right-up is the
result generate by Clipper with none-zero fill type, the right-down is
even-odd.Obviously 'none-zero' filltype is correct in this test.
I am looking for the codes that handling overlape polygons in curaengine,
but I didnt find it,so I was confused how dese curaengine fix this.
Follwing is the layer view of the model's first layer in Cura, and Cura
makes the correct layerpart.
[image: test2]
<https://cloud.githubusercontent.com/assets/22258646/23219628/93131a26-f95a-11e6-8804-5aa4aac6c729.jpg>
Waiting for answers ,thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/467>, or mute the thread

**Comment by zidong404** [comment]
Thanks! A model is loaded into a mesh or split into a meshgroup? Where the function "determines which fill the is used"  be implemented.Could you give me some clues.

**Comment by BagelOrb** [comment]
Meshgroups are what's printed in one-at-a-time mode. When you print
normally there's only one meshgroup.

Overlapping meshes are subtracted from each other, while overlapping
volumes within a single mesh are unioned.

The subtraction is done in a function called carveMultipleVolume or
something similar with the word 'carve' in it.

Op 23 feb. 2017 02:37 schreef "zidong404" <notifications@github.com>:

Thanks! A model is loaded into a mesh or split into a meshgroup? Where the
function "determines which fill the is used" be implemented.Could you give
me some clues.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/467#issuecomment-281863140>,
or mute the thread

**Comment by zidong404** [comment]
Thanks a lot,BagelOrb，I've got it.
