### ISSUE TITLE
Spiralize bottom layer

### ISSUE THREAD

**Issue by N3MIS15** [Ultimaker/CuraEngine#51]
When using spiralize the bottom layers are being put down in a mesh pattern. Its like cura is only laying down every second line.

<img src="http://i39.tinypic.com/e14zme.jpg" />
<img src="http://i39.tinypic.com/sq76uq.jpg" />

It makes the spiralize setting useless for vases (where it should shine)..
Is there any reason behind this behaviour? Or is it a bug?

**Comment by makevoid** [comment]
If you can't fix this use Tweak at Z plugin to increase the flow for the lower layers

**Comment by nicolinux** [comment]
Daid, I'd like to ask you to re-open this issue. There are others that have the exact same problem and the extruder is working fine (UM2, no skipping, high temp). The mesh pattern looks completely regular and deliberate and it is presumably a bug (model or Cura). Also apart from the mesh pattern at the bottom, every 2nd layer looks like a circular brim where the filament strands are far apart too (the green lines in the screenshot).
![spiralize](https://cloud.githubusercontent.com/assets/1069286/7634558/03c8b596-fa5c-11e4-8feb-0308b73d86b1.png)

**Comment by BagelOrb** [comment]
This is causing the reported problems on my UM2 as well.
Note that I thought I did hear my extruder slipping.

Perhaps this is an issue with the defaults. Daid, I suppose you mean 'layer height', by "thickness"?
Maybe we should have lower printing speed defaults for spiralize mode then? Or the obvious thing to do would be to lower the 'layer height', i.e. not have "very thick lines in spiralize mode"...

I think the alternating bottom pattern is intentional; you're just experiencing the same underextrusion issue.

**Comment by BagelOrb** [comment]
I cannot reproduce the problem in the new Cura. It seems to have been solved.
