### ISSUE TITLE
Connecting via command socket

### ISSUE THREAD

**Issue by masklu** [Ultimaker/CuraEngine#526]
If I connecting via command socket like this

CuraEngine.exe connect 127.0.0.1:12312 -j fdmprinter.def.json
 welcome

 when I slice a stl file, what should I send

**Comment by BagelOrb** [comment]
Maybe @nallath can help you better.

Op 24 mei 2017 04:59 schreef "masklu" <notifications@github.com>:

If I connecting via command socket like this

CuraEngine.exe connect 127.0.0.1:12312 -j fdmprinter.def.json
welcome

what should I send.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/526>, or mute the thread

**Comment by awhiemstra** [comment]
When using the command socket, we expect a binary stream of data that is provided in a format implemented in the [Arcus] library. Arcus defines a wire format and uses [Protobuf] for serializing the actual data. The Protobuf protocol file is included in this repository (Cura.proto in the root directory).

Note that the socket connection is intended for two-way communication between a front-end application and the engine. It is not intended as a generic server.

[Arcus]: https://github.com/ultimaker/libArcus
[Protobuf]: https://github.com/google/protobuf

**Comment by BagelOrb** [comment]
[answered]
