### ISSUE TITLE
How to set the infill direction

### ISSUE THREAD

**Issue by vvirguezv** [Ultimaker/CuraEngine#542]
Hi everyone, 
I'm working on a project with a 3D Printing Machine (Da Vinci 1.0), I have a BIG problem, i need to make some rectangular specimens to prove it in a tension test but i want to know **how to change or set the infill direction in each printing by myself.**
Because the printer already has the default infill direction (normally 45º)  in order to save time and material.

Thanks!

**Comment by smartavionics** [comment]
Hi, since cura 2.5, you can set the direction of the infill (and also the skins). There are Infill Line Directions and  Skin Line Directions settings. What you enter is a comma separated sequence of angles surrounded by square brackets. The defaults are [45, 135]. The angles are used cyclically. i.e. 45, 135, 45, 135, ...
I have a part which needs to have a lot of infill in a particular direction so I use [45, 0, 135, 0].
