### ISSUE TITLE
GCODE has invalid headers when output to file

### ISSUE THREAD

**Issue by jeromechrist** [Ultimaker/CuraEngine#660]
### Description
GCODE has invalid headers when output to file while the executable standard output is correct

### Steps to Reproduce
`CuraEngine.exe slice -v -j "C:\Program Files\Ultimaker Cura 3.0\resources\definitions\ultimaker3.def.json" -l "C:\Users\jerome.christ\Desktop\cura\screw.stl" -o "C:\Users\jerome.christ\Desktop\cura\output.gcode"`

This will produce a GCODE with correct instructions except for the headers, from the console :
![image](https://user-images.githubusercontent.com/2547646/33270308-e61ed5d0-d383-11e7-87d3-7336d2b67cdc.png)

But the written file has incorrect headers, when send to the UM3 it is deemed as invalid :
![image](https://user-images.githubusercontent.com/2547646/33270378-2345dd8c-d384-11e7-945b-b20db81bf7ed.png)

**Reproduces how often:**
Always

### Versions

CuraEngine.exe v.3.0.3 used in command line
OS : Windows 10
CURA_ENGINE_SEARCH_PATH = "C:\Program Files\Ultimaker Cura 3.0\resources\definitions;C:\Program Files\Ultimaker Cura 3.0\resources\extruders"

**Comment by Ghostkeeper** [comment]
This also reproduces for me.

It seems like the problem here is that when slicing via command line, `gcodeExport`'s output stream is `std::cout` or the target file, and then it has to put the header in front before any of the g-code has been output, so before any g-code is known and before the bounding box has been set. When slicing via an Arcus socket, the output is `commandSocket`'s `gcode_output_stream` which can be finalized later.
