### ISSUE TITLE
Layer 1 is empty if initial layer thickness < layer height 

### ISSUE THREAD

**Issue by JohnHouwer** [Ultimaker/CuraEngine#69]
If i set the initial layer thickness smaller than the layer height. The first Layer is empty and the print starts with the second layer (layer height + initial layer thickness).

Versions:
Cura: On branch SteamEngine
SteamEngine: On branch master

Let me know if you need additional information. Thanks.

**Comment by tzminversion** [comment]
I have also just found this issue.

I want to print at 0.2 mm and an initial layer height of 0.1 mm, seems the results are unexpected. From what I can observe and as written in issue 152 the initial layer height is now 0.3 mm. I would expect it to be 0.1 ;)

This comes in handy when you want to have a nice flat bottom at 0.1 mm but print at 0.2 mm for the rest of the model. I normally print at 0.1 mm and set the initial layer height to 0 so that the first layer is 0.1 mm.

As a workaround, I adjusted the initial layer height to 0 with layer height 0.2 mm and moved the bed up to compensate.

**Comment by BagelOrb** [comment]
It seems that this problem does not exist for the new Cura. (Standard settings, layer_height_0=0.01)

**Comment by whypurplishblue** [comment]
This bug is still there in Cura 15.04.4. Tested with:
Layer Heights = 0.2
Advanced > Quality > inital layer thickness = 0.1. 

Used the workaround by setting the initial layer thickness to 0.16 in order to get the skirt to print

**Comment by daid** [comment]
We have Cura 2.1 beta our right now:
https://ultimaker.com/en/community/20538-cura-21-open-beta-has-been-released
(Note the beta download link isn't that obvious)
