### ISSUE TITLE
Feature request: Skirt around the convex-hull of first layer

### ISSUE THREAD

**Issue by mikeq3** [Ultimaker/CuraEngine#8]
The skirt is currently laid down around the build platform contact points of the model.  The raft and support material end up printed over the skirt.  A large model with small contact points ends up with very little skirt.

**Comment by BagelOrb** [comment]
@gsmith-to please do create a pull request with the convex-hull algorithm :)

**Comment by gsmith-to** [comment]
OK. I adapted the code to work in ClipperLib types back in December, just need to work out the git mechanics. Do I need permission to create a branch? I don't see that option coming up in this repo.

There's a clipper_convex_hull.h, and clipper_convex_hull.cpp, I propose to just add them to the src/utils directory. There's also a small test suite (which builds the routine as a python extension, and runs the test in python) which I can put in src/utils/test.

**Comment by BagelOrb** [comment]
please change your code such that function names start with a lower case letter.

**Comment by BagelOrb** [comment]
Also you should start struct names with an upper case letter, put the return type of a function on the same line, starting bracket '{' on a new line, space ' ' after if, so "if (...".

Moreover, it seems you use a lot of code for something which could be done in a lot less, I would think.
I would think you would just walk through a linked list and whenever you find an element for which convex3 doesn't hold, backtrack and remove all for which it doesn't hold. I would expect such a thing to be coded in a few dozen of lines, instead of a few hundred.

**Comment by gsmith-to** [comment]
I've made those mods, and run the code through 'astyle' so it's formatted much more like the existing project code. All spaces now, instead of an odd mix of tabs and spaces, too. 'astyle' has a lot of options but not one to "'put space after 'if', but not after 'for' and 'while'", so I did that manually :-)

Also removed unused calculation of minx,maxx (left over from previous incarnation of the code).

It could indeed be done in much less code, but it would then become very slow when processing many points. There is method similar to what you describe, which is fast, and can be used when the input is known to be a single, proper polygon (not self-intersecting); you can just go around and cut out the non-convex segments. For the general case, where you could have any set of points in any order (including possible duplicates), that doesn't work; the 'simplest' approach consists of building a convex hull as you go; for each new point, if it's outside, you modify the hull to include it, if it's inside, you discard it. But after a while the hull is pretty large, and most of the new points are likely to be inside, and to establish that each point is inside you need to compare it to all edges of the hull. Even for the 'outside' points, you will usually need to go around much of the hull until you find which part of the hull it's outside.

The method I used is based on Andrew's Monotone Chain algorithm ( http://en.wikibooks.org/wiki/Algorithm_Implementation/Geometry/Convex_hull/Monotone_chain ) - I go from low y to high y, through the sorted points, and build the left and right hulls. For a large list, it will sort the points in O( n logn) and then take less time than that (about O(n)) to make the hull.

An improvement is that I build the two sides in a single pass rather than one followed by the other. It's easy to tell which side the next point belongs to, if any; points which fall within the triangle defined by the two ends of the two partial hulls, and the 'max y' point, can be trivially discarded - this can easily be a large fraction of the points - whereas the basic Andrews algorithm adds these, and takes them out a bit later, and then does it again on the other side.

The core of the algorithm is in 40 lines - the middle 'for' loop - the rest is setup and takedown, and dealing with special cases (for instance, there may be one 'bottom' point of minimum y, or there may be several, and the algorithm needs to examine these to establish whether there is one distinct 'bottom' point, or two, in the hull, and remove any 'inboard' or duplicate points, before it starts).

For the immediate application - finding a skirt - it wouldn't matter much if it was slow (bearing in mind that if you throw the entire first layer of a really complex print at it, the simple approach could be *really* slow) but I had already coded this for another project, and it's good to have a fast robust algorithm in case you want it for some other reason where you'd be calling it far more often.

**Comment by BagelOrb** [comment]
I'm sorry to say your code is still not up to standard. You should have adapted it to cura::Polygon instead of Clipper::Path .

Though I am excited about your convex hull algorithm, I don't know where I should use it. I agree with you that a much simpler approach would be to approximate the convex-hull by doing a large offset and then a large inset.

I was thinking it might come in handy for a better path order optimizer which tries to avoid objects. Not really sure though.

**Comment by gsmith-to** [comment]
No need to apologize, happy to work on the integration as I find the time. I'll take a shot at fully integrating it myself, replacing the current skirt; I just had a look at that and it seems fairly straightforward.
It seems to me the approximation by offset/inset is only really simpler if you don't have a convex hull routine handy. And I agree with your comments from december, that it could be problematic due to corners and self-intersecting polygons. And if you have say, an H-shaped outline, the insets would either be removed completely, or not at all,  according to how big they are are relative to the offset. Which would be strange.
So, tasks I will look at next are (1) add method to SliceLayer to generate its convex hull (2) convex hull expander which rounds corners (3) integration into existing skirt routine.
