### ISSUE TITLE
Skirt not going around all the objects on the build plate

### ISSUE THREAD

**Issue by dotps1** [Ultimaker/CuraEngine#851]
**Application Version**

3.4.1

**Platform**

Windows 10 Pro x64

**Qt**

**PyQt**

**Display Driver**

18.30.11.01-180827a-332601E-RadeonSoftwareAdrenalin

**Steps to Reproduce**

I added 8 objects to the print bed, then used the "Arrange All Models" option.  

**Actual Results**

The skirt is going right through one of the objects.

![image](https://user-images.githubusercontent.com/1016996/45587394-da4e2f00-b8d2-11e8-91ba-79de152baa39.png)

**Expected results**

The skirt should be going around all the objects.

**Additional Information**

is there a way to manually adjust the  skirt placement?
[CCR10_X_Y_Tensioners.zip](https://github.com/Ultimaker/CuraEngine/files/2385795/CCR10_X_Y_Tensioners.zip)

**Comment by dotps1** [comment]
I just wanted to add, if I move the object down -.5mm the skirt goes correctly, but it looks like its flat based on this:  
![image](https://user-images.githubusercontent.com/1016996/45587548-08347300-b8d5-11e8-80b1-c02982e52f77.png)
And if I manually move it with the mouse, it snaps down to the plate so I would think its flat and on the plate.

**Comment by nallath** [comment]
The red just shows it's overhang, not that it's actually flat. The fact that it snaps on the build plate does not mean that the object is flat. It could well be that it used the lowest part to put it on the build plate. Based on the behavior that moving it a bit below it does work, my guess is that the bottom of the model isn't quite flat.

**Comment by nallath** [comment]
You could check out the PrintOrientation plugin. Although it's not quite what you need, it will probably fix your issue. The plugin tries to find an orientation in such a way that it has as little overhang as possible. So if your print is already close to that, it will most likely also make the minute change so that it's as flat as possible on the buildplate.

**Comment by rburema** [comment]
(In Cura-frontend:) There is 'Lay Flat' under the the 'Rotate' icon in the sidebar on the left, but that only works with the nearest face and when the model _can_ actually be laid flat. (Which means that it won't really work all too well when a single model is really a group of objects which all may or may not have some small visually almost invisible height-offset, because we of course shouldn't just 'break' a users' model.)

Since this isn't really a bug in the engine on examination, I'm going to close it. Feel free to make a feature request in Cura (frontend), but keep in mind that we could choose to defer it, or skip it completely, depending on all kinds of different factors, like available dev.-time.
