### ISSUE TITLE
[3.6.0] Extra skin wall count does not work for thin skins

### ISSUE THREAD

**Issue by mihai-dumitresq** [Ultimaker/CuraEngine#977]
**Application Version**
3.6.0

**Steps to Reproduce**
Set Extra Skin Wall Count to 1 then prepare. I'm using https://www.thingiverse.com/thing:2975429 to test but scaled to 50% of the size.

**Actual Results**
Skin areas that are very thin omit the extra skin wall. Only larger skin areas have the extra skin concentric wall (as expected).
See right thin wall: 
![screenshot from 2019-01-20](https://user-images.githubusercontent.com/299015/51434413-9475ee80-1c57-11e9-8412-c64dec281155.png)

**Expected results**
All skin areas have the extra skin concentric wall.

**Additional Information**
Also note how jittery the travel/print path for that thin skin on the right wall. It's creating a lot of vibration when trying to print said part on an Ender 3, even with travel&print jerk as low as 8mm/s.

**Comment by Ghostkeeper** [comment]
This is because the gap filling technique is not actually skin, though it has the same colour. There should actually be a wall there, but the wall doesn't fit so it fills it with small line segments.

Adding a wall around those line segments makes no sense because the line segments are only there when a wall didn't fit any more.

The idea is also to then combine these line segments into a more continuous line so that it doesn't vibrate that much. That last bit should work a bit better in 4.0.
