### ISSUE TITLE
Outer Perimeter First

### ISSUE THREAD

**Issue by totalretribution** [Ultimaker/CuraEngine#98]
Hi,
Could an option to print the outer Perimeter before any other Perimeter be added.
I find that although overhangs are more difficult with outer perimeter first an objects dimensions tend to be more accurate.

For reference KISSlicer calls this option "Loops go from inside to Perimeter" and Slic3r calls this option "External perimeters first"

Thanks
Neil

**Comment by lerouxb** [comment]
I find that printing the outer perimeter walls first does wonders for tight tolerances. Holes print a bit more accurate and tiny gaps such as in [this thing](http://www.thingiverse.com/thing:184919) come out much closer to what's specified in the STL file. Sometimes you want to prioritise surface finish and sometimes tight tolerances are more important. Would be nice to be able to choose which you prefer.

In a desperate attempt to get holes and tiny gaps like the example above to come out the intended size I recently tried the latest version of Slic3r again and I found that this setting really helps. The other relevant useful feature in Slic3r is to shrink objects slightly "inwards". This solved all my problems with holes. You can't always easily modify the model slightly for every printer out there and I think the slicer is the right place to adjust for that sort of thing. See [this page](http://manual.slic3r.org/troubleshooting/dimension-errors) for more details.

(Ended up switching back to Cura because Slic3r crashes constantly and prints fail because of different things. But now I have to stick to printing things for which I can get the OpenSCAD files so I can adjust holes and gaps..)

**Comment by totalretribution** [comment]
Embarrassingly I think that @daid may have accepted this pull request originally however sadly due to my inexperience and stupidity with git it was not merged successfully. I have however re-added a new pull request which will work when merged.

**Comment by totalretribution** [comment]
@lerouxb This is currently being discussed at the pull request #177 if your interested.
