### ISSUE TITLE
Z-hop not working with combing mode over max distance

### ISSUE THREAD

**Issue by bealparslan** [Ultimaker/CuraEngine#981]
Settings:

- Combing mode: on
- Max comb distance with no retract: 5mm
- Z Hop: on
- Z Hop height: 0.6mm

In a printing; if travel distance over 5mm, retracting happened but z-hop not working.

**LayerPlan.cpp line 373**
`        // path is not shorter than min travel distance, force a retraction`
`        path->retract = true;`
`        if (comb == nullptr) ` << problem is here, **maybe**..
`        {`
`            path->perform_z_hop = extruder->settings.get<bool>("retraction_hop_enabled");`
`        }`

**Comment by Ghostkeeper** [comment]
This is indeed expected behaviour. Combing prevents hitting any walls of the print, if possible. So if combing was possible (`comb != nullptr`), you won't hit any walls. Z-hop is another method to prevent hitting any walls. If you're not going to hit any walls, Z-hop will not be necessary.

Retraction might still be necessary to prevent underextrusion after the move due to oozing.
